### ISSUE TITLE
Boos.Mysql does not work with latest boost version

### ISSUE THREAD

**Issue by nesc1** [anarthal/mysql#52]
Hi, I was trying the library with the latest boost version and it seems there is some problem with it.

Trying with boost version 1.76 everything works as expected, but with boost version 1.77 connection action always return:

Bad file descriptor (9)

on the asio connection.

That code is a bit hard to understand, so if you could help understanding what is the problem will be great.
Best regards,
Nuno

**Comment by anarthal** [comment]
Fixed by 86e0eacd6ad3f47a201c75067f3327ac1e12ee36.

**Comment by nesc1** [comment]
Hi, I today tested with boost 1.79 and it still not work given the following error:

`Error: Physical connect failed: Connection refused [system:111], error code: system:111`

code is simple doing a connect:
```

    //[tutorial_connection
    // The execution context, required to run I/O operations
    boost::asio::io_context ctx;
    // The SSL context, required to establish TLS connections.
    // The default SSL options are good enough for us at this point.
    boost::asio::ssl::context ssl_ctx (boost::asio::ssl::context::tls_client);
    // The object defining the connection to the MySQL server.
    boost::mysql::tcp_ssl_connection conn (ctx.get_executor(), ssl_ctx);
    // The username and password to use
    boost::mysql::connection_params params (
        username, // username
        pwd  // password
    );
    boost::asio::ip::tcp::endpoint ep(boost::asio::ip::address_v4::loopback(),boost::mysql::default_port);
    conn.connect(ep, params);

```

Mysql version is:

```
❯ mysql --version
mysql  Ver 15.1 Distrib 10.3.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

Best regards,
Nuno

**Comment by madmongo1** [comment]
This is an error at the network layer.
Your server is either not listening or firewalled.

**Comment by anarthal** [comment]
As @madmongo1 pointed out, this means that the physical TCP connection could not be established. If you are running the example as is (i.e. `boost_mysql_example example_user example_password`), your server is assumed to be listening on localhost.

When typing `mysql --version`, `mysql` is likely using a UNIX socket connection instead of TCP. Could you please post the result of running the following command?

```
mysql -u root --host localhost --port 3306 --protocol tcp
```

**Comment by nesc1** [comment]
yes indeed sorry for that i didn't notice that...but unfortanelly i'm not bein able to use the new version on a normal sql server

i tested with your examples and it always give me this:

```
❯ ./example/boost_mysql_example_query_sync <user> <pwd> <host>
Error: The server does not support the minimum required capabilities to establish the connection, error code: mysql:65539
```

and in my original code it makes the connection but any sql fails with exception...

**Comment by anarthal** [comment]
This is very likely caused by TLS being disabled or misconfigured on the server. `tcp_ssl_connection` by default requires that the server supports TLS. You can force the same behavior in `mysql`:

```
mysql -u root --host localhost --port 3306 --protocol tcp --ssl-mode required
```

If TLS is not properly configured, the above will fail. You can either configure TLS properly by using MySQL config files (https://dev.mysql.com/doc/refman/8.0/en/using-encrypted-connections.html) or use plaintext connections by using `tcp_connection` instead.

**Comment by nesc1** [comment]
I @anarthal thank you for your help, indeed using tcp_connection is the key to make a successful connection.

Trying your command it does not know the option ssl-mode:

```
❯ mysql -u <user> -p --host localhost --port 3306 --protocol tcp --ssl-mode required
mysql: unknown option '--ssl-mode'
```
but when i do some selects I'm getting this kind of errors:

```
[E][43:58] DB error: An unexpected value was found in a server-received message, error code: An unexpected value was found in a server-received message (65540)
select telegramid,balance from userbalance
[E][43:58] DB error: Mismatched sequence numbers, error code: Mismatched sequence numbers (65538)
select userid, otherid from automaticeventassignment
[E][43:58] DB error: Mismatched sequence numbers, error code: Mismatched sequence numbers (65538)
```

Do you know what is happening?

**Comment by anarthal** [comment]
Could you please share a gist with the entire code you're using, please?

**Comment by nesc1** [comment]
can you explain what is a gist ... sorry don't know how to do it...

**Comment by anarthal** [comment]
A way to share code: https://gist.github.com/
Google is your friend.

**Comment by nesc1** [comment]
(thank you..yep indeed i could do a google search before i asked :P)

Humm ok that's strange, where the code throws the exception, only doing that select does not cause the problem (https://gist.github.com/nesc1/93231380f10b7d8a9cad2fbdc8adcfba), only with connect and doing the problematic select...  It must something before... but with previous version it does not happen, but with this new one it happens... I only changed the source code of the boost::mysql and change from fetch_xxx calls to read_xxx calls...

**Comment by anarthal** [comment]
From the errors you're getting, it seems your problem is related to not fully reading resultsets before engaging into further operations.

When you call `connection::query` or `prepared_statement::execute` you *must* read the resultset you get *completely* (a successful call to `resultset::read_all` does the trick) before engaging into any subsequent operation, including further queries, closing statements or preparing other statements. From your description, your code is failing to do that under some circumstance.

**Comment by nesc1** [comment]
But in my code I always use read_all(..) or something like this:

```
boost::mysql::row row;
while (result.read_one(row))
{
//i do not break these operations
}
```

**Comment by nesc1** [comment]
never mind... I already loose too much time with this... what I did to fix the problem was simple drop the table and create it again in mysql and it worked after this... don't really know what was the problem...

@anarthal thank you anyway for your help.

**Comment by nesc1** [comment]
this still happen... even if i drop the table and recreate it again... the boost::mysql does not read the column float or double but decimal reads... returning:
`An unexpected value was found in a server-received message (65540)`
still don't understand why...

**Comment by Jackson-soft** [comment]
boost 1.79 have the same error

**Comment by anarthal** [comment]
I'm still unable to reproduce the issue. I'm running [this code](https://gist.github.com/anarthal/2a91848debecf0681ef86718144df0a3) under Boost 1.80, clang 12, Linux and MySQL 8.0.30.

Could you please provide a minimum reproducible example in a public gist where the issue occurs? Otherwise I have no way to look deeper into this issue.

**Comment by anarthal** [comment]
@Jackson-soft are you experimenting the same issue as @nesc1?
